name: Check Terraform Format
description: "Check that terraform files in the PR are formatted"

inputs:
  files:
    description: "List of file paths to check"
    required: true
  terraform_version:
    description: "The version of Terraform CLI to use, defaults to `latest`."
    default: latest
    required: false

runs:
  using: "composite"
  steps:
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Terraform format check
      id: tf-fmt
      shell: bash
      run: |
        exit_code=0
        for file in ${{ inputs.files }}; do
          terraform fmt -check $file || exit_code=1
        done
        exit $exit_code
