name: Check Terraform Lint rules
description: "Check that terraform files in the PR are respecting tflint rules"

inputs:
  config_file_path:
    description: "Relative path to config file"
    required: true
  files:
    description: "List of file paths to check"
    required: true
  os:
    description: "The OS that's used to run action"
    default: ubuntu-latest
    required: false


runs:
  using: "composite"
  steps:
  - uses: actions/checkout@master
  - name: Python Linter
    uses: sunnysid3up/python-linter@master
    with:
      source: "${{ inputs.files }}"
      mypy-options: "--ignore-missing-imports --show-error-codes"
      pylint-options: "--rcfile=setup.cfg"


