name: Check Javascript Vulnerabilities.
description: "Check javascript vulnerabilities to the PR"

inputs:
  frontend_config_file:
    description: "A working directory passed from the caller workflow"
    required: true
  backend_config_file:
    description: "A working directory passed from the caller workflow"
    required: false
  node_version:
    description: "The version of nodejs to use, defaults to `14`."
    default: "14"
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Node.js ${{ inputs.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.node_version }}

    - name: Check Javascript Vulnerabilities.
      shell: bash
      working-directory: ${{ inputs.frontend_config_file }}
      run: |
           ls -lrt ${{ inputs.frontend_config_file }}
           npx audit-ci --config="${{ inputs.frontend_config_file }}"
      
      
    - name: Check Javascript Vulnerabilities.
      shell: bash
      working-directory: ${{ inputs.backend_config_file }}
      run: |
           ls -lrt ${{ inputs.backend_config_file }}
           npx audit-ci --config="${{ inputs.backend_config_file }}"
