name: Check Terraform Lint rules
description: "Check that terraform files in the PR are respecting tflint rules"

inputs:
  config_file_path:
    description: "Relative path to config file"
    required: true
  files:
    description: "List of file paths to check"
    required: true
  os:
    description: "The OS that's used to run action"
    default: ubuntu-latest
    required: false


runs:
  using: "composite"
  steps:
    - name: Run ShellCheck
      uses: azohra/shell-linter@latest
      with:
          path: "${{ inputs.files }}"
