name: Check Dockerfile Lint rules.
description: "Check that Dockerfiles in the PR are respecting hadolint rules"

inputs:
  config_file_path:
    description: "Relative path to config file"
    required: true
  files:
    description: "List of file paths to check"
    required: true
  os:
    description: "The OS that's used to run action"
    default: ubuntu-latest
    required: false


runs:
  using: "composite"
  steps:
    - name: test
      run: |
           pwd
           ls -lart
    - name: 'Yamllint'
      run: |
         ls -lart
         pwd
         sudo apt install yamllint -y
         exitcode=0
         for file in ${{ needs.changed_sh_files_job.outputs.changed_files }}; do
              yamllint -c ${{ inputs.config_file_path }} ${{ $files }} || exitcode=1
         done
         exit $exit_code
         
