name: Check Dockerfile Lint rules.
description: "Check that Dockerfiles in the PR are respecting hadolint rules"

inputs:
  files:
    description: "List of file paths to check"
    required: true

runs:
  using: "composite"
  steps:
    - name: 'Yamllint'
      run: |
        sudo apt install yamllint -y
        exit_code=0
        for file in ${{ inputs.files }}; do
          yamllint $file || exit_code=1
        done
        exit $exit_code
