name: CI
on:
  push:
     tags:
       - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2    
    - name: Copy zip file to S3 Bucket.
      run: |
           app_version=`cat VERSION`
           zip -r test1$app_version.zip .
           aws s3 cp test1$app_version.zip s3://saiteju1997/builds/test1/
    - name: Send email notification.
      run: |      
           unified_version=`cat VERSION`
           python3 scripts/send_email.py "GitHub Actions Build is ${{ job.status }} for ${{ github.repository }}" "steju480@gmail.com" "m.sandhyarani03@gmail.com" "  Hi,
           
               This  mail is to confirm that your build is ${{ job.status }} for ${{ github.repository }},
               The below repositories are updated:
               
               $unified_version
               
               
           
           
           
           Warm Regards,
           OTA Team.
           
           
           
           
           
           " ${{secrets.AWS_ACCESS_KEY_ID}} ${{secrets.AWS_SECRET_ACCESS_KEY}}
           
