name: CI
on:
  push:
   
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2    
    - name: Copy zip file to S3 Bucket.
      run: |
           app_version=`cat VERSION`
           zip -r test1-v$app_version.zip .
           aws s3 cp test1-v$app_version.zip s3://saiteju1997/builds/test1/
    - name: Updating token
      run: |    
           sed 's/https:\/\//https:\/\/x-access-token:${{secrets.GH_TOKEN}}/g' token
           cat token
    
 
