name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ main ]

jobs:
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Install SSH key"
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.TEST_GITHUB_KEY }}
          known_hosts: 'dummy'
          name: id_rsa # optional
          if_key_exists: fail 
    
      - name: "Add github as known host"
        run: |
             ls -lart
             pwd
             ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - name: "Configure GitHub to use private go modules"
        run: |
             git config --global url."git@github.com:Saiteju1997".insteadOf https://github.com/Saiteju1997
             cat ~/.gitconfig
      - name: "Build images"
        run: make container
