name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ main ]

jobs:
       
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: test commands.
        run: |
             #echo "${{ github.event.before }}" 
             echo "${{ github.event.pull_request.base.sha }}" 
             echo "${{ github.event_name == 'pull_request' }}" 
