name: Create new tags or update existing ones

on:
  push:
    branches:
      - main
    outputs:


jobs:
  # TODO: filter these to changed only to not run matrix for all actions & workflows

  get_all_actions_job:
    runs-on: ubuntu-latest
    outputs:
      any_changed: ${{ steps.get-changed-modules.outputs.any_changed }}
      changed_dirs: ${{ steps.get-changed-modules.outputs.changed_dirs }}
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: get-changed-files
        # yamllint disable-line rule:line-length
        uses: Tirumaladevib/test1/.github/actions/changed-files-since-last-success@main
        with:
          files_to_match: |
            .github/workflows/**
            .github/actions/**
          get_changed_dirs: true
          github_token: ${{ secrets.GH_TOKEN }}
          separator: "|"
          workflow_id: self-tag.yml

      - name: Get changed tf modules
        id: get-changed-modules
        uses: Tirumaladevib/test1/.github/actions/changed-files-dir@main
        with:
          changed_dirs: ${{ steps.get-changed-files.outputs.changed_files }}
          separator: '|'

  # tag_job:
  #   runs-on: ubuntu-latest
  #   needs: get_all_actions_job
  #   if: needs.get_all_actions_job.outputs.any_changed == 'true'
  #   strategy:
  #     max-parallel: 6
  #     matrix: ${{ fromJson(needs.get_all_actions_job.outputs.changed_dirs) }}
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - uses:  ./.github/actions/tag-semver
  #       id: semver
  #       with:
  #         tag_prefix: "${{ matrix.prefix }}/v"
  #         major_pattern: "BREAKING CHANGE"
  #         minor_pattern: "/^(feat|chore)[^a-z]/"
  #         change_path: ${{ matrix.path }}

  # tag_job_success:
  #   if: ${{ always() }}
  #   runs-on: ubuntu-latest
  #   needs: tag_job
  #   steps:
  #     - name: Check tag_job status
  #       if: ${{ needs.tag_job.result != 'success' && needs.tag_job.result != 'skipped' }}
  #       run: exit 1