name: Create new tags or update existing ones

on:
  push:
    branches:
      - main

jobs:
  # TODO: filter these to changed only to not run matrix for all actions & workflows

  get_all_actions_job:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-all-actions.outputs.matrix }}
      any_changed: ${{ steps.get-changed-files.outputs.any_changed }}
      changed_files: ${{ steps.get-changed-files.outputs.changed_files }}
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: get-changed-files
        # yamllint disable-line rule:line-length
        uses: Tirumaladevib/test1/.github/actions/changed-files-since-last-success@main
        with:
          files_to_match: |
            .github/actions/**
            .github/workflows/**
          get_changed_dirs: true
          github_token: ${{ secrets.GH_TOKEN }}
          separator: "|"
          workflow_id: self-tag.yml
      - name: Print outputs
        run: |
          echo "any_changed: ${{ steps.get-changed-files.outputs.any_changed }}"
          echo "changed_files: ${{ steps.get-changed-files.outputs.changed_files }}"
          echo "matrix: ${{ steps.get-changed-files.outputs.matrix }}"
      - name: Get all actions
        id: get-all-actions
        shell: bash
        run: |
          # Get directories as an array for all github actions that we version
          readarray -d '' actions < <(find .github/actions -mindepth 1 -maxdepth 1 -type d)
          # Get directories as an array for all github workflows that we version
          readarray -d '' workflows < <(find .github/workflows/ -type f ! -name 'self-*')

          workflows_json=$(
            echo "${workflows[@]}" |  jq -c -R 'split(" ")
            | map({prefix: ("w_" + split("/")[-1] | split(".")[0]), path: (.)})')

          actions_json=$(
            echo "${actions[@]}" |  jq -c -R 'split(" ") | map({prefix: ("a_" + split("/")[-1]), path: (.)})')

          actions_n_workflows_json=$(echo "${workflows_json} ${actions_json}" |  jq -s -c add)
          echo "matrix={\"include\":$actions_n_workflows_json}" >> $GITHUB_OUTPUT
