name: Create new tags or update existing ones

on:
  push:
    branches:
      - main

jobs:
  # TODO: filter these to changed only to not run matrix for all actions & workflows

  get_all_actions_job:
    runs-on: ubuntu-latest
    outputs:
      any_changed: ${{ steps.get-changed-files.outputs.any_changed }}
      changed_files: ${{ steps.get-changed-files.outputs.changed_files }}
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: get-changed-files
        # yamllint disable-line rule:line-length
        uses: Tirumaladevib/test1/.github/actions/changed-files-since-last-success@main
        with:
          files_to_match: |
            .github/actions/**
            .github/workflows/**
          get_changed_dirs: true
          github_token: ${{ secrets.GH_TOKEN }}
          separator: "|"
          workflow_id: self-tag.yml
      - name: Get changed tf files and dirs
        id: get-changed-files-dirs
        # yamllint disable-line rule:line-length
        uses: Tirumaladevib/test1/.github/actions/changed-files-dir@main
        with:
          changed_files_dirs: ${{ steps.get-changed-files.outputs.changed_files }}
      - name: Print outputs
        run: |
          echo "any_changed: ${{ steps.get-changed-files-dirs.outputs.any_changed }}"
          echo "changed_files: ${{ steps.get-changed-files-dirs.outputs.changed_files }}"
          #echo "matrix: ${{ steps.get-changed-files-dirs.outputs.matrix }}"
