name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ main ]

jobs:
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: echo "this is for testing"
      - name: "Build images"
        run: | 
             echo "echo 0 test"
             exit 0
             echo "echo 1 test"
             exit
             make container
      - name: "lw-scanner"
        id: lw-scanner
        env: 
          BINS: api worker
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          PROJECT:         testproject
          REGISTRY:        us.gcr.io/test-sample
          ARCH:            amd64
          OS:              linux
        run:  |
              VERSION=`git describe --tags --always --dirty`
              TAG="${VERSION}__${OS}_${ARCH}"
              sudo apt-get update -y
              sudo apt-get -y install curl
              curl -L https://github.com/lacework/lacework-vulnerability-scanner/releases/latest/download/lw-scanner-linux-amd64 -o lw-scanner
              chmod +x lw-scanner
              for bin in $BINS; do
                  echo "$REGISTRY/$PROJECT-$bin:$TAG"
                  echo "failure"
              done
      - name: Check if vulnerabilites were found and step failed.
        if: steps.lw-scanner.outcome == 'failure'
        run:  | 
              echo "Vulnerabilities found and step failed succesfully."
      - name: fail test
        run:  |
              echo "Vulnerabilities found and step failed succesfully."
              exit -1
      - name: "test"
        run:  |
              echo "build is completed"
        
        


