name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses:  actions/checkout@v2
    - name: first job
      run: |
           echo "CRITICAL_VULNS_FOUND=$(cat VERSION)" > $GITHUB_ENV
           echo $CRITICAL_VULNS_FOUND
    - name: testing second job output.
      run: |
        echo "$CRITICAL_VULNS_FOUND"
        cat VERSION
        echo "this is testing"
        if [[ "${CRITICAL_VULNS_FOUND}" -ge 1 ]]; then
            pwd
            ls -lrt
            echo "working"
            exit 1
            
        fi       
           
      shell: bash     
    - name: last test
      run: echo "this is last testing"
           


        
        

