name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v2
      - name: first job
        run: |
             ls -lrt
             echo "{LW_SCANNER_EXIT_CODE}={test}" >> $GITHUB_ENV
             echo $LW_SCANNER_EXIT_CODE
      - name: testing second job output.
        run: |
             export FOO=bar
             echo $FOO
             echo "::set-env name=FOO::$FOO"
      - name: testing job       
        run: echo $FOO
              

