name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses:  actions/checkout@v2
    - name: first job
      run: |
           echo "test_value=$(cat VERSION)" > $GITHUB_ENV
           echo $test_value
    - name: testing second job output.
      run: |
        if [[ "${test_value}" != 2 ]]; then
            pwd
            ls -lrt
            echo "working"
            
        fi   
        exit 0    
           
      shell: bash     
           


        
        

