name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: testing job.
        run: |
             echo "sample"
  archive-build-artifacts:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: "Install SSH key"
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.TEST_GITHUB_KEY }}
          known_hosts: 'dummy'
          name: id_rsa # optional
          if_key_exists: fail 
    
      - name: "Add github as known host"
        run: |
             ls -lart
             pwd
             ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - name: "Configure GitHub to use private go modules"
        run: |
             git config --global url."git@github.com:Saiteju1997".insteadOf https://github.com/Saiteju1997
             cat ~/.gitconfig
      - name: "Build images"
        run: | 
             make container
      - name: "Lacework inline scanner"
        env: 
          BINS: api worker
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
        run:  |
              PROJECT=testproject
              REGISTRY=us.gcr.io/test-sample
              git describe --tags --always --dirty
              VERSION=`git describe --tags --always --dirty`
              echo $VERSION
              ARCH=amd64
              OS=linux
              TAG=$VERSION__$OS_$ARCH
              sudo apt-get update -y
              sudo apt-get -y install curl
              curl -L https://github.com/lacework/lacework-vulnerability-scanner/releases/latest/download/lw-scanner-linux-amd64 -o lw-scanner
              chmod +x lw-scanner
              for bin in $BINS; do
                  echo "$REGISTRY/$PROJECT-$bin:$TAG"
              done

         
