name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses:  actions/checkout@v2 
    - name: last test
      env: 
        BINS: api worker
        PROJECT:         issuance
        REGISTRY:        us.gcr.io/mrt-issuer-d-1b41
        ARCH:            amd64
        OS:              linux  
      run: |
           VERSION=`git describe --tags --always --dirty`
           TAG="${VERSION}__${OS}_${ARCH}"
           imagename=$REGISTRY/$PROJECT-$bin
           echo $imagename
           for bin in $BINS; do
                  echo "$REGISTRY/$PROJECT-$bin:$TAG"
                  mkdir -p ${GITHUB_WORKSPACE}/evaluations/$REGISTRY/$PROJECT-$bin/$TAG/
                  cd ${GITHUB_WORKSPACE}/evaluations/$REGISTRY/$PROJECT-$bin/$TAG/
                  touch evaluation_1.json
                  echo ".cve.critical_vulnerabilities" >> evaluation_1.json
                  CRITICAL_VULNS_FOUND=$(cat ${GITHUB_WORKSPACE}/evaluations/$REGISTRY/$PROJECT-$bin/$TAG/evaluation_*.json | jq '.cve.critical_vulnerabilities')
           done
           
           


        
        

