name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses:  actions/checkout@v2 
    - name: last test
      env: 
        BINS: api worker
        PROJECT:         issuance
        REGISTRY:        us.gcr.io/mrt-issuer-d-1b41
        ARCH:            amd64
        OS:              linux  
      run: |
           VERSION=1.0.0
           TAG="${VERSION}__${OS}_${ARCH}"
           echo $imagename
           for bin in $BINS; do
                  imagename=$REGISTRY/$PROJECT-$bin
                  CRITICAL_VULNS_FOUND=`cat VERSION`
                  if [[ "${CRITICAL_VULNS_FOUND}" -ge 0 ]]; then
                       pwd
                       ls -lrt
                       echo "working"
                       exit 1
              
                 fi 
           done
           
           


        
        

