name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ main ]

jobs:
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    
      - name: "Build images"
        run: | 
             make container
      - name: "Lacework inline scanner"
        env: 
          BINS: api worker
          LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          PROJECT:         testproject
          REGISTRY:        us.gcr.io/test-sample
          ARCH:            amd64
          OS:              linux
          TAG:             "${{ VERSION }}__${{ OS }}_${{ ARCH }}"
        run:  |
              VERSION=`git describe --tags --always --dirty`
              sudo apt-get update -y
              sudo apt-get -y install curl
              curl -L https://github.com/lacework/lacework-vulnerability-scanner/releases/latest/download/lw-scanner-linux-amd64 -o lw-scanner
              chmod +x lw-scanner
              for bin in $BINS; do
                  echo "$REGISTRY/$PROJECT-$bin:$TAG"
              done

         
