name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v2
      - name: testing second job output.
        run:  |
              mkdir -p sai/tej
              ls -lrt
              pwd
            
  archive-build-artifacts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-ersion: [14, 6]
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-ersion }}
      - name: test
        run: |
             ls -lrt
             pwd
        


