name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ san-test ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v2
      - name: first job
        run: |
             echo "CRITICAL_VULNS_FOUND=(cat VERSION)" > $GITHUB_ENV
             if: "${CRITICAL_VULNS_FOUND} -ge 1"
             echo "2>1"
      - name: testing second job output.
        run: |
             echo $CRITICAL_VULNS_FOUND
     

              

