name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v2
      - name: first job
        run: |
             ls -lrt
             echo "{LW_SCANNER_EXIT_CODE}={test}" >> $GITHUB_ENV
             echo $LW_SCANNER_EXIT_CODE
      
      - name: testing second job output.
      #  if: ${CRITICAL_VULNS_FOUND} -ge 1 
        run:  |
          a=10
          b=10
          if $a=$b; then
              echo "success"
          fi
              

