name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses:  actions/checkout@v2 
    - name: last test
      env: 
        BINS: api worker
        PROJECT:         issuance
        REGISTRY:        us.gcr.io/mrt-issuer-d-1b41
        ARCH:            amd64
        OS:              linux  
      run: |
           TAG="${VERSION}__${OS}_${ARCH}"
           for bin in $BINS; do
                  echo $REGISTRY/$PROJECT-$bin:$TAG
           done
           for bin in $BINS; do
                  imagename=$REGISTRY/$PROJECT-$bin
                  CRITICAL_VULNS_FOUND=`cat VERSION`
                  HIGH_VULNS_FOUND=`cat VERSION1`
                 # if [[ "${CRITICAL_VULNS_FOUND}" -ge 1 ]] && [[ "${HIGH_VULNS_FOUND}" -ge 1 ]] ; then
                  if [ \( "$CRITICAL_VULNS_FOUND" -ge 1 -o "$HIGH_VULNS_FOUND" -ge 1 \) ]
                  then
                        echo "vulnerabilities found"
                #        exit 1
                  fi
           done
           
    - name: final test.
      run: |
           sudo apt-get update -y;sudo apt-get -y install curl
           curl -L https://github.com/lacework/lacework-vulnerability-scanner/releases/latest/download/lw-scanner-linux-amd64 -o lw-scanner;chmod +x lw-scanner
              
           


        
        

