name: Publish GitHub Actions Artifacts Example

on:
  push:
    branches: [ san-test ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v2
      - name: first job
        if: ${CRITICAL_VULNS_FOUND}  -ge 1
        run: |
             echo "CRITICAL_VULNS_FOUND=$(cat VERSION)" > $GITHUB_ENV
      - name: testing second job output.
        run: |
             echo $CRITICAL_VULNS_FOUND
     

              

